# Generated by Django 5.0.2 on 2024-03-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='Country',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United states'), ('CA', 'Canada'), ('MX', 'Mexico')], default='IN', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='designation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='resource',
            name='emp_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='emp_role',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='resource',
            name='practice',
            field=models.CharField(max_length=40),
        ),
    ]
