# Generated by Django 5.0.2 on 2024-03-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_alter_resource_country_alter_resource_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
