# Generated by Django 5.0.2 on 2024-03-06 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_resource_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='emp_class',
        ),
        migrations.AddField(
            model_name='resource',
            name='dol',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='emp_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Resigned', 'Resigned')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='Country',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United states'), ('CA', 'Canada'), ('MX', 'Mexico'), ('OT', 'Others')], default='IN', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='employee_type',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Contractor', 'Contractor'), ('Global Employee', 'Global Employee')], default='Employee', max_length=30),
        ),
        migrations.AlterField(
            model_name='resource',
            name='mode_of_employ',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Consultant', 'Consultant'), ('Contingent worker', 'Contingent worker'), ('Business User', 'Business User')], default='Employee', max_length=30),
        ),
        migrations.AlterField(
            model_name='resource',
            name='practice',
            field=models.CharField(choices=[('Dotnet', 'Dotnet'), ('Solutioning', 'Solutioning'), ('Quality Assurance', 'Quality Assurance'), ('Delivery Excellence', 'Delivery Excellence')], default='Dotnet', max_length=40),
        ),
    ]
