# Generated by Django 5.0.2 on 2024-03-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_remove_resource_emp_class_resource_dol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='dol',
            field=models.DateField(blank=True, null=True),
        ),
    ]
